name:                sudoku-perf
version:             0.1.0.0
github:              "dberf/sudoku-perf"
license:             BSD3
author:              "Daniel Berg"
maintainer:          "danibberg@gmail.com"
copyright:           "2018 Daniel Berg"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/sudoku-perf#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.5
- parallel >= 3.2
- deepseq >= 1.4

library:
  source-dirs: src

executables:
  sudoku-perf-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -eventlog
    - -O2
    dependencies:
    - sudoku-perf

tests:
  sudoku-perf-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sudoku-perf
